/**
 * Finishes a release build: moves the artifacts into `builds/`, then deletes
 * the intermediates left behind in `src-tauri/target/release`.
 *
 *     builds/soundcloud.exe            the portable binary
 *     builds/msi/*.msi                 the Windows Installer package
 *     builds/nsis/*-setup.exe          the NSIS setup program
 *
 * The intermediates run to ~1.6 GB across ~1400 files, and the build cannot be
 * made to emit fewer: Cargo writes an rlib, an rmeta and a dep-info file for
 * every crate it compiles, and a Tauri app is ~410 crate builds deep. Dropping
 * them afterwards is safe - they exist only to let the next build skip work,
 * and a full release rebuild here takes about 2.5 minutes. Run
 * `npm run app:build:keep` when that trade is not worth it.
 */
import { existsSync, mkdirSync, readdirSync, renameSync, rmSync } from "node:fs";
import { basename, join } from "node:path";

const RELEASE = "src-tauri/target/release";
const BUILDS = "builds";

/** Regenerated by the next build; `bundle/` too, once emptied below. */
const INTERMEDIATES = [
  "deps",
  "build",
  "wix",
  "nsis",
  "incremental",
  "examples",
  ".fingerprint",
  "bundle",
];

function move(from, toDir) {
  mkdirSync(toDir, { recursive: true });
  const to = join(toDir, basename(from));
  clear(to);
  renameSync(from, to);
  console.log(`  ${to}`);
}

/**
 * Clears the way for a new artifact. Rebuilding the same version replaces what
 * is already there - but the exe in `builds/` is the one you actually run, and
 * Windows refuses to delete a live one. It will happily *rename* one though,
 * so a running copy is parked beside the new build instead of failing it.
 */
function clear(path) {
  try {
    rmSync(path, { force: true });
    return;
  } catch (e) {
    if (e.code !== "EPERM" && e.code !== "EBUSY") throw e;
  }
  const parked = `${path}.old`;
  try {
    rmSync(parked, { force: true });
  } catch {
    /* an older copy is running too; the rename below reports it */
  }
  renameSync(path, parked);
  console.log(`  (in use - previous build parked as ${basename(parked)})`);
}

/** Found rather than spelled out, so renaming the crate does not break this. */
function inDir(dir, ext) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .map((f) => join(dir, f));
}

console.log("moved into builds/:");
for (const exe of inDir(RELEASE, ".exe")) move(exe, BUILDS);
for (const msi of inDir(join(RELEASE, "bundle", "msi"), ".msi")) move(msi, join(BUILDS, "msi"));
for (const setup of inDir(join(RELEASE, "bundle", "nsis"), ".exe")) {
  move(setup, join(BUILDS, "nsis"));
}

for (const dir of INTERMEDIATES) {
  rmSync(join(RELEASE, dir), { recursive: true, force: true });
}
console.log(`trimmed ${RELEASE}/`);
